catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import catalog_index_view, catalog_list_view, catalog_detail_view, group_detail_view, import_catalog_view, control_detail_view

app_name = 'catalog'
urlpatterns = [path('', catalog_index_view, name='catalog_index_view'),
               path('list', catalog_list_view.as_view(), name='catalog_list_view'),
               path('<int:pk>', cache_page(60 * 15)(catalog_detail_view.as_view()), name='catalog_detail_view'),
               path('import/<str:catalog_id>', import_catalog_view, name='import_catalog_view'),
               path('control/<int:pk>', control_detail_view.as_view(), name='control_detail_view'),
               path('group/<int:pk>', group_detail_view.as_view(), name='group_detail_view'),
               ]

common/urls.py
from django.urls import path

from common.views import permalink_view, database_status_view, auth_view, base64_list_view, base64_detail_view, \
    upload_file, add_resource_view, add_links_view, add_props_view

app_name = 'common'
urlpatterns = [path('p/<str:p_uuid>', permalink_view, name='permalink'),
               path('db_status/', database_status_view, name='db_status'),
               path('auth/', auth_view, name='auth_view'),
               path('f/list', base64_list_view.as_view(), name='base64_list'),
               path('f/detail/<int:pk>', base64_detail_view, name='base64_detail'),
               path('f/add', upload_file, name='upload_file'),
               # path('f/render/<int:pk>', base64_render_view, name='base64_render'),
               path('resource/add', add_resource_view, name='add_resource_view'),
               path('link/add', add_links_view, name='add_links_view'),
               path('prop/add', add_props_view, name='add_props_view'),
               ]

component/urls.py
from django.urls import path
from component.views import component_list_view, component_detail_view, policy_component_form_view, cloud_service_component_form_view, component_form_view, social_media_component_form_view

app_name = 'component'
urlpatterns = [
    path('', component_list_view, name='component_list_view'),
    path('<int:pk>', component_detail_view.as_view(), name='component_detail_view'),
    path('add/', component_form_view, name='component_form_view'),
    path('add/policy/', policy_component_form_view, name='policy_component_form_view'),
    path('add/cloud_service/', cloud_service_component_form_view, name='cloud_service_component_form_view'),
    path('add/social_media/', social_media_component_form_view, name='social_media_component_form_view')
    ]

ctrl_profile/urls.py
from django.urls import path

from ctrl_profile.views import profile_list_view, profile_detail_view, createProfileView

app_name = 'ctrl_profile'
urlpatterns = [path('', profile_list_view.as_view(), name='profile_list_view'),
               path('<int:pk>', profile_detail_view.as_view(), name='profile_detail_view'),
               path('new', createProfileView.as_view(), name='create_profile_view')]

opal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from common.views import index_view

urlpatterns = [path('', index_view, name='home_page'),
               path('admin/', admin.site.urls),
               path('catalog/', include('catalog.urls'), name='catalog'),
               path('common/', include('common.urls'), name='common'),
               path('component/', include('component.urls'), name='component'),
               path('profiles/', include('ctrl_profile.urls'), name='profiles'),
               path('ssp/', include('ssp.urls'), name='ssp'),
               re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
               path("accounts/", include("django.contrib.auth.urls")),
               re_path(r'^_nested_admin/', include('nested_admin.urls')),
               ]

if settings.ENVIRONMENT != 'production':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.ENABLE_SAML == 'True':
    urlpatterns_saml = [path("sso/<idp_slug>/", include("sp.urls")),]
    urlpatterns.extend(urlpatterns_saml)


# if settings.ENABLE_OIDC: <- Disabled until we re-implement OIDC
#     urlpatterns.extend([re_path(r'^oidc/', include('mozilla_django_oidc.urls')), ])

handler404 = 'common.views.error_404_view'

ssp/urls.py
from django.urls import path

from ssp.views import ssp_list_view, ssp_detail_view, import_ssp_view, ssp_form_view

app_name = 'ssp'
urlpatterns = [
    path('', ssp_list_view.as_view(), name='ssp_list_view'),
    path('<int:pk>', ssp_detail_view.as_view(), name='ssp_detail_view'),
    path('import/<str:ssp_file>', import_ssp_view, name='import_ssp_view'),
    path('add/', ssp_form_view, name='add_new_ssp_view'),
    ]

templates/auth.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <h1 class="mt-2 mb-4 pb-2 border-bottom">OPAL Authentication</h1>
        {% if user.is_authenticated %}
            <p><strong>{% with user=user idp=idp|default:"Django" %}You are logged in as {{ user }} via {{ idp }}.</strong></p>
            <p>
                {% if idp %}
                    <a class="btn btn-sm btn-secondary" href="{{ idp.get_verify_url }}">Verify</a>
                    <a class="btn btn-sm btn-secondary" href="{{ idp.get_logout_url }}">Log Out</a>
                {% else %}
                    <a class="btn btn-sm btn-secondary" href="{% url 'admin:logout' %}?next=/">Log Out</a>
                {% endif %}
            </p>
            {% endwith %}
        {% else %}
            <p><strong>You are not logged in.</strong></p>
            <p><strong>Available Authentication Services are:</strong></p>
            <ul class="list-group">
                {% for idp in idps %}
                    <li class="list-group-item">
                        <strong>{{ idp }}</strong>:
                        <span class="float-right">
                            <a class="btn btn-sm btn-secondary" href="{{ idp.get_login_url }}?next={{ next }}">Login</a>
                        </span>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if ENABLE_DJANGO_AUTH == 'True' %}
            <a href="{% url 'admin:login' %}">Login</a> using Django built in authentication
        {% endif %}
    </div>
{%  endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>OPAL</title>

    {# Load the tag library #}
    {% load bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    {% load static %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
    <!--Begin Form media -->
    {{ form.media }}
    {{ wizard.form.media }}
    <!--End Form media -->

    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>

    <!-- Custom styles for this template-->
    <link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'admin/css/forms.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">

    <script src="{% static '/admin/js/admin/RelatedObjectLookups.js' %}"></script>


</head>
<body id="page-top">
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">OPAL<sup>2</sup></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:catalog_index_view' %}">Catalogs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ctrl_profile:profile_list_view' %}">Profiles</a>
        </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownComponents" role="button" data-bs-toggle="dropdown" aria-expanded="false">Components</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownComponents">
                  <li><a class="collapse-item" href="{% url 'component:component_list_view' %}">Component List</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="collapse-item" href="{% url 'component:policy_component_form_view' %}">Add New Policy</a></li>
                  <li><a class="collapse-item" href="{% url 'component:cloud_service_component_form_view' %}">Add New Cloud Service</a></li>
                  <li><a class="collapse-item" href="{% url 'component:social_media_component_form_view' %}">Add New Social Media Account/Service</a></li>
                  <li><a class="collapse-item" href="{% url 'component:component_form_view' %}">Add Other Component</a></li>
              </ul>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'ssp:ssp_list_view' %}">System Security Plans</a>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'common:base64_list' %}">Files</a></li>
        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUtilities" role="button" data-bs-toggle="dropdown" aria-expanded="false">Utilities</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownUtilities">
            <li><a class="collapse-item" href="/admin/">Admin Dashboard</a></li>
            <li><a class="collapse-item" href="{% url 'common:db_status' %}">Database Status Report</a></li>
          </ul>
        </li>

        <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href={% url 'common:auth_view' %} >Logout</a>
            {% else %}
                <a class="nav-link" href={% url 'common:auth_view' %} >Login</a>
            {% endif %}
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<!-- Begin Page Content -->
<div style="padding-left: 25px; padding-top: 50pt; width: 90%">
    {% block content %}

    {% endblock %}
</div>
<!-- /.container-fluid -->
<!-- End of Main Content -->

<!-- Footer -->
<footer class="sticky-footer bg-white">
{#<div class="container my-auto">#}
{#    {% if user.is_authenticated %}#}
{#        {% with user=user idp=idp|default:"Django" %}#}
{#        <p><strong>You are logged in as {{ user }} via {{ idp }}.</strong></p>#}
{#        {% endwith %}#}
{#    {% else %}#}
{#        <p><strong>You are not logged in.</strong></p>#}
{#    {% endif %}#}
{#</div>#}
</footer>
<!-- End of Footer -->


<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

</body>

</html>

templates/db_status.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<ul>
{% for item in model_list %}
    <li>{{ item }}</li>
{% empty %}
    <li>Sorry, something went wrong.</li>
{% endfor %}
</ul>
<!-- /.container-fluid -->
{% endblock %}

templates/error.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>One or more errors occurred..</h1>
<h5>This is definitely not Dan's fault.</h5>
    <ul>
    {% if err_msg %}
        <h3>{{ err_msg }}</h3>
    {% else %}
        <li>Dude, even I'm not sure what happened.</li>
    {% endif %}
    </ul>
<!-- /.container-fluid -->
{% endblock %}

templates/generic_checkbox_list_options.html
{% for item in options %}
<input type="checkbox" id="{{ item.value }}" name="{{ item.name }}" value="{{ item.value }}">
<label for="{{ item.value }}"> {{ item.display }}</label><br>
{% endfor %}

templates/generic_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{{ context.to_html | safe}}
{% endblock %}

templates/generic_dropdown_list_options.html
<option value="None">----</option>
{% for item in options %}
<option value="{{ item.value }}">{{ item.display }}</option>
{% endfor %}

templates/generic_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>{{ title }}</h1>
    <div>{{ content | safe }}</div>
    <div>
    {% if form_list %}
        {% for form in form_list %}
            <form method="post" novalidate class="form-floating" action="{{ form.action }}">
            {% include "generic_form_helper.html" with form=form %}
            <p class="button" style="padding-top: 15px"; ><button type="submit">Submit</button></p>
            </form>

        {% endfor %}
    {% else %}
        <form method="post" novalidate class="form-floating" action="{{ form.action }}">
        {% include "generic_form_helper.html" with form=form %}
        <p class="button" style="padding-top: 15px"; ><button type="submit">Submit</button></p>
        </form>
    {% endif %}
    </div>
    <script>
        $(document).ready(function() {
          $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
          });

          $('.timepicker').timepicker({
            format: 'hh:ii:ss',
            autoclose: true,
            showMeridian: false,
          });

          $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            showClear: true
          });
        });
      </script>
{% endblock %}

templates/generic_form_helper.html
{% csrf_token %}
<input type="hidden" name="next" value="{{ form.next_page }}">
<h1>{{ form.form_title }}</h1>
<div class="row-form-errors">{{ form.non_field_errors }}</div>
{% for hidden_field in form.hidden_fields %}
  <div class="row-form-errors">{{ hidden_field.errors }}</div>
  {{ hidden_field }}
{% endfor %}
<div class="form-floating d-table">
  {% for field in form.visible_fields %}
      <div class="form-row d-table-row">
          <div class="form-label d-table-cell text-nowrap" style="vertical-align: middle" onmouseover="{{ field.help_text }}">
              {{ field.label_tag }}
          </div>
          <div class="row-form-errors text-nowrap" style="vertical-align: top; color: red">{{ field.errors }}</div>
          <div class="form-control d-table-cell" style="vertical-align: middle">{{ field }}</div>
      </div>
  {% endfor %}
</div>

templates/generic_html_helper.html
{{ content | safe}}

templates/generic_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>{{ title }}</h1>
    <a href="{{ add_url }}">Add New {{ model_name }}</a>
    <ul>
{% for item in context_list %}
    <li><a class="collapse-item" href="{{ item.get_permalink }}">{{ item }}</a></li>
{% empty %}
    <li>No objects of this type are available</li>
{% endfor %}
</ul>
{% endblock %}

templates/generic_template.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>{{ title }}</h1>
    <div>{{ content | safe}}</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>Step 1: Import Catalogs</h1>
    <p>The OSCAL catalog model is a collection of controls, represented as a control catalog. The OSCAL catalog model was designed to represent security and privacy controls in standardized, machine-readable formats. The OSCAL catalog model standardizes the representation of control definitions from different sources (e.g., SP 800-53, ISO/IEC 27002, COBIT 5) allowing control information to be easily searched, imported, and exported by applications using a common format.</p>
    {% if user.is_superuser %}
    <p>OPAL allows an administrator to define which catalogs can be imported. To add a catalog, first add it to <a href="{% url 'admin:catalog_available_catalog_list_changelist' %}">the list of approved catalogs</a></p>
    {% endif %}
    {% if catalog_list %}
    <p>Click on any of the following links to import the catalog:</p>
    <ul>
        {{ catalog_list | safe}}
    </ul>
    {% endif %}
    <p>You can click on the <b>Catalogs</b> menu item to see a list of available profiles or create new ones.</p>
<h1>Step 2: Creating a Profile</h1>
    A profile is a set of controls selected by the organization. This can be as simple as a direct import of a catalog. Or you can create more complex profiles that include controls from multiple catalogs.  The profile is also where you will tailor your controls to meet your organizations specific needs and risk tolerance.  You must create a profile to use a set of controls in a system security plan, so OPAL automatically creates a basic profile for you when you import a catalog. You can click on the <b>Profiles</b> menu item to see a list of available profiles or create new ones.
<h1>Step 3: Creating Components</h1>
    <p>Components are the individual parts that make up a system.  You can define a single component that includes your entire system, but a more valuable approach is to define modular components that can be inherited by multiple systems.  For example, you can create a component for a shared database resource or a server image. Components can also be policies or procedures that can be applied to multiple systems.</p>
    <p>When creating a component you can also define specific controls that are implemented by the component.  The details of the implementation can then be imported into System Security Plans that include the component.</p>
    <p>Again, as a convenience, OPAL automatically creates a Policy Component for each Control Group in your imported Catalog.  Click on the <b>Components</b> menu item to see a list of all your components and create new ones.
<h1>Step 4: Creating the SSP</h1>
    <p>Finally, you will use OPAL to create a System Security Plan. In this final step you will describe the information system and idnetify the components, users, resources, etc. that make up the system. Click on the <b>System Security Plans</b> menu item to see a list of all your components and create new ones.</p>
<h1>Files</h1>
    <p>OPAL can also serve as a file repository for any artifact associated with your organizations security program. Click on the <b>Files</b> menu item to see a list of available files or add new ones.</p>
<h1>Utilities</h1>
    <p>The <b>Utilities</b> menu item provides convenient links to a few useful tools.</p>
    <ul>
    <li><b>Admin Dashboard</b> - Accessable only to System Administrors, the Admin Dashboard allows you to add/edit/delete any object in OPAL. This is the primary interface for adding and editing components. It is also where you can add catalogs, set up SAML authentication, and many other administrative tasks.</li>
    <li><b>Database Status Report</b> - This report shows the number of rows in each table in the OPAL database.  It is useful as a sanity check if you are running imports but not seeing any results.</li>
    </ul>

{% endblock %}